### ISSUE TITLE
Can I use this with Amazon Aurora?

### ISSUE THREAD

**Issue by bestickley** [aidansteele/rdsconn#6] opened 2023-06-28 15:52 UTC
Hi, I tried to use this with Amazon Aurora for port forwarding but ran into this error:
```bash
aws ec2-instance-connect open-tunnel \
  --private-ip-address 10.0.2.44 \
  --instance-connect-endpoint-id eice-0c5db94cacd12345 \
  --remote-port 5432 \
  --local-port 5432
Listening for connections on port 5432.
[1] Accepted new tcp connection, opening websocket tunnel.
2023-06-28 11:50:56,333 - awscli.customizations.ec2instanceconnect.websocket - ERROR - [1] Encountered error with websocket: (9, 'Bad file descriptor')
[1] Closing tcp connection.
[2] Accepted new tcp connection, opening websocket tunnel.
2023-06-28 11:51:00,000 - awscli.customizations.ec2instanceconnect.websocket - ERROR - [2] Encountered error with websocket: (9, 'Bad file descriptor')
[2] Closing tcp connection.
[3] Accepted new tcp connection, opening websocket tunnel.
2023-06-28 11:51:03,750 - awscli.customizations.ec2instanceconnect.websocket - ERROR - [3] Encountered error with websocket: (9, 'Bad file descriptor')
[3] Closing tcp connection.
[4] Accepted new tcp connection, opening websocket tunnel.
2023-06-28 11:51:07,363 - awscli.customizations.ec2instanceconnect.websocket - ERROR - [4] Encountered error with websocket: (9, 'Bad file descriptor')
[4] Closing tcp connection.
[5] Accepted new tcp connection, opening websocket tunnel.
2023-06-28 11:51:11,025 - awscli.customizations.ec2instanceconnect.websocket - ERROR - [5] Encountered error with websocket: (9, 'Bad file descriptor')
[5] Closing tcp connection.
[6] Accepted new tcp connection, opening websocket tunnel.
```

Any ideas?

**Comment by aidansteele** [comment] 2023-06-29 00:46
Unfortunately this is no longer possible, it seems ~yesterday the service added extra validation to only allow ports 22 and 3389. I'll close this issue as a duplicate of #5

**Closed by aidansteele** 2023-06-29 00:46 UTC
